---

# Configuration file for pre-commit
# https://pre-commit.com/

repos:

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 'v3.4.0'
    hooks:
    - id: check-added-large-files  # Prevent giant files from being committed
    - id: check-ast  # Simply check whether files parse as valid python
    - id: check-builtin-literals  # Require literal syntax when initializing empty or zero Python builtin types
    - id: check-case-conflict  # Check for files with names that would conflict on a case-insensitive filesystems
    - id: check-docstring-first  # Checks for a common error of placing code before the docstring
    - id: check-executables-have-shebangs  # Checks that non-binary executables have a proper shebang
    - id: check-json  # Attempts to load all json files to verify syntax
    - id: check-merge-conflict  # Check for files that contain merge conflict strings
    - id: check-symlinks  # Checks for symlinks which do not point to anything
    - id: check-toml  # Attempts to load all TOML files to verify syntax
    - id: check-vcs-permalinks  # Ensures that links to vcs websites are permalinks
    - id: check-xml  # Attempts to load all xml files to verify syntax
    - id: check-yaml  # Attempts to load all yaml files to verify syntax
    - id: debug-statements  # Check for debugger imports and py37+ breakpoint() calls in python source
    - id: detect-private-key  # Checks for the existence of private keys
    - id: end-of-file-fixer  # Makes sure files end in a newline and only a newline
    - id: fix-byte-order-marker  # Removes UTF-8 byte order marker
    - id: mixed-line-ending  # Replaces or checks mixed line ending
    - id: name-tests-test  # Assert that files in tests/ end in _test.py
    - id: requirements-txt-fixer  # Sorts entries in requirements.txt and removes incorrect entry for pkg-resources
    - id: trailing-whitespace  # Trims trailing whitespace

  - repo: https://github.com/psf/black
    rev: '21.4b2'
    hooks:
    - id: black

  - repo: https://gitlab.com/pycqa/flake8
    rev: '3.8.4'
    hooks:
    - id: flake8

  - repo: https://github.com/timothycrosley/isort
    rev: '5.8.0'
    hooks:
    - id: isort

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: 'v1.8.0'
    hooks:
    - id: python-check-blanket-noqa
    - id: python-no-log-warn
    - id: python-no-eval
    - id: rst-backticks
    - id: python-use-type-annotations
    - id: text-unicode-replacement-char

  - repo: https://github.com/asottile/pyupgrade
    rev: 'v2.15.0'
    hooks:
    - id: pyupgrade
